services:

  backend:
    image: khanhne1234/mern-backend:1.0
    network_mode: "host"
    extra_hosts:
      - "ac-jrn9ry9-shard-00-00.ud6xdyp.mongodb.net:159.143.64.95"
      - "ac-jrn9ry9-shard-00-01.ud6xdyp.mongodb.net:159.143.63.127"
      - "ac-jrn9ry9-shard-00-02.ud6xdyp.mongodb.net:159.143.63.91"
    env_file:
      - mern-demo/server/.env

  frontend:
    image: khanhne1234/mern-frontend:2.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
